M48
; DRILL file {KiCad (6.0.7)} date Wed 28 Sep 2022 12:10:16 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-28T12:10:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X44.294Y-52.256
X44.294Y-120.056
X255.894Y-52.256
X255.894Y-120.256
T0
M30
